name: FastAPI Testing

on: push

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:16-alpine
        env:
          POSTGRES_DB: postgres
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - name: Setup PDM
        uses: pdm-project/setup-pdm@v4
        with:
          python-version-file: backend/pyproject.toml
          cache: true
          cache-dependency-path: backend/pdm.lock

      - name: Install Dependencies
        run: pdm install --dev
        working-directory: backend

      - name: Run Tests
        env:
          # docker is not used in GitHub Actions with a simple setup
          POSTGRES_HOSTNAME: localhost
        run: pdm run pytest
        working-directory: backend
