name: FastAPI Testing

on: push

jobs:
  test:
    runs-on: ubuntu-latest

    # FIXME: Add PostgreSQL as a dependency to test database connection
    # services:
    #   postgres:

    steps:
      - uses: actions/checkout@v4

      - name: Setup PDM
        uses: pdm-project/setup-pdm@v4
        with:
          python-version-file: backend/pyproject.toml
          cache: true
          cache-dependency-path: backend/pdm.lock

      - name: Install Dependencies
        run: pdm install
        working-directory: backend

      - name: Run Tests
        run: pdm run pytest
        working-directory: backend
